//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pay2cell.com/", ConfigurationName="SRService.SRServiceSoap")]
    public interface SRServiceSoap {
        
        // CODEGEN: Generating message contract since message DoRechargeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pay2cell.com/DoRecharge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SRService.DoRechargeResponse DoRecharge(SRService.DoRechargeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pay2cell.com/")]
    public partial class Information : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Credentials apiCredentialsField;
        
        private string mobileToRechargeField;
        
        private string billerAccountNumberField;
        
        private decimal amountField;
        
        private byte rechargeViaField;
        
        private byte typeOfRechargeField;
        
        private int serviceCodeField;
        
        private int operatorCodeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Credentials ApiCredentials {
            get {
                return this.apiCredentialsField;
            }
            set {
                this.apiCredentialsField = value;
                this.RaisePropertyChanged("ApiCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MobileToRecharge {
            get {
                return this.mobileToRechargeField;
            }
            set {
                this.mobileToRechargeField = value;
                this.RaisePropertyChanged("MobileToRecharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BillerAccountNumber {
            get {
                return this.billerAccountNumberField;
            }
            set {
                this.billerAccountNumberField = value;
                this.RaisePropertyChanged("BillerAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public byte RechargeVia {
            get {
                return this.rechargeViaField;
            }
            set {
                this.rechargeViaField = value;
                this.RaisePropertyChanged("RechargeVia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte TypeOfRecharge {
            get {
                return this.typeOfRechargeField;
            }
            set {
                this.typeOfRechargeField = value;
                this.RaisePropertyChanged("TypeOfRecharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pay2cell.com/")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private string deviceIDField;
        
        private string newPasswordField;
        
        private int operatingSystemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("DeviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int OperatingSystem {
            get {
                return this.operatingSystemField;
            }
            set {
                this.operatingSystemField = value;
                this.RaisePropertyChanged("OperatingSystem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoRecharge", WrapperNamespace="http://www.pay2cell.com/", IsWrapped=true)]
    public partial class DoRechargeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.pay2cell.com/")]
        public SRService.Information Information;
        
        public DoRechargeRequest() {
        }
        
        public DoRechargeRequest(SRService.Information Information) {
            this.Information = Information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoRechargeResponse", WrapperNamespace="http://www.pay2cell.com/", IsWrapped=true)]
    public partial class DoRechargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pay2cell.com/", Order=0)]
        public string DoRechargeResult;
        
        public DoRechargeResponse() {
        }
        
        public DoRechargeResponse(string DoRechargeResult) {
            this.DoRechargeResult = DoRechargeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SRServiceSoapChannel : SRService.SRServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRServiceSoapClient : System.ServiceModel.ClientBase<SRService.SRServiceSoap>, SRService.SRServiceSoap {
        
        public SRServiceSoapClient() {
        }
        
        public SRServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRService.DoRechargeResponse SRService.SRServiceSoap.DoRecharge(SRService.DoRechargeRequest request) {
            return base.Channel.DoRecharge(request);
        }
        
        public string DoRecharge(SRService.Information Information) {
            SRService.DoRechargeRequest inValue = new SRService.DoRechargeRequest();
            inValue.Information = Information;
            SRService.DoRechargeResponse retVal = ((SRService.SRServiceSoap)(this)).DoRecharge(inValue);
            return retVal.DoRechargeResult;
        }
    }
}
